@startuml
start
repeat :초음파 센서로 장애물과의 거리를 측정;
    if (거리가 15cm 이상인가?) then (yes)
        :거리에 따라 속도를 결정;
        :결정된 속도로 이동;
    else (no)
        :정지한다;
    endif
:잠시 기다린다;
repeat while() is (계속 반복);
stop

start
repeat :초음파 센서로 장애물과의 거리를 측정;
    if (거리가 15cm 이상인가?) then (yes)
        :거리에 따라 속도를 결정;
        :결정된 속도로 이동;
        :빨간 LED를 끈다;
        :초록색 LED를 켠다;
        :주행중으로 상태를 변경한다;
        :기다린 횟수를 0으로 만든다;
    else (no)
        if (주행 중이었는가?) then (yes)
            :정지한다;
            :초록색 LED를 끈다;
            :빨간 LED를 켠다;
            :삐삐 소리를 낸다;
            :기다린 횟수를 1로 만든다;
            :대기중으로 상태를 변경한다;
        else (no)
            if (5번 미만 기다렸는가?) then (yes)
                :기다린 횟수를 1 증가시킨다;
            else (no)
                :방향을 오른쪽으로 조금 회전한다;
                :기다린 횟수를 0으로 만든다;
                :주행중으로 상태를 변경한다;
            endif
        endif
    endif
:잠시 기다린다;
repeat while() is (계속 반복);
stop

@enduml
